# Generated by Django 3.0.7 on 2020-06-14 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200612_1431'),
        ('cart', '0006_auto_20200613_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product', 'product', 'size', 'color')},
        ),
    ]
