# Generated by Django 3.1.5 on 2021-01-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_promocode_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
            options={
                'unique_together': {('product', 'size', 'color', 'quantity')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=70)),
                ('delivery', models.CharField(choices=[('pick_up', 'Pick up'), ('courier', 'Courier')], default='pick_up', max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.CharField(blank=True, choices=[('receipt', (('CR', 'Cash'), ('BCR', 'Bank card'), ('GCR', 'Gift card'))), ('pay_now', (('ICN', 'installment card'), ('BKN', 'Visa, Mastercard, Belcard'), ('EN', 'ERIP'))), ('partial', 'Partial payment'), ('legal_persons', 'Legal persons')], default='CR', max_length=30)),
                ('promocode', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('payment', 'Payment'), ('availabilty', 'Availability'), ('shipping', 'Shipping'), ('delivery_date', 'Delivery date')], default='created', max_length=30)),
                ('total_price', models.IntegerField(default=0)),
                ('user_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('BIC', models.CharField(blank=True, max_length=9, null=True)),
                ('UNP', models.CharField(blank=True, max_length=9, null=True)),
                ('IBAN', models.CharField(blank=True, max_length=28, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_address', models.CharField(blank=True, max_length=200, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('supply_agreement', models.BooleanField(default=True)),
                ('items', models.ManyToManyField(to='cart.CartItem')),
            ],
            options={
                'unique_together': {('user_ip', 'date_created')},
            },
        ),
    ]
