# Generated by Django 3.1.3 on 2020-12-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('receipt', (('CR', 'Cash'), ('BCR', 'Bank card'), ('GCR', 'Gift card'))), ('pay_now', (('ICN', 'installment card'), ('BKN', 'Visa, Mastercard, Belcard'), ('EN', 'ERIP'))), ('partial', 'Partial payment'), ('legal_persons', 'Legal persons')], default='CR', max_length=30),
        ),
    ]
