# Generated by Django 3.1.3 on 2020-12-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
