# Generated by Django 3.1.3 on 2020-12-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201205_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='email@mail.ru', max_length=70),
        ),
    ]
