# Generated by Django 3.1.3 on 2020-12-04 21:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20201205_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
