# Generated by Django 3.1.3 on 2020-12-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
