# Generated by Django 3.1.5 on 2021-01-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_promocode_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='size', to='products.Size', verbose_name='size'),
        ),
    ]
