# Generated by Django 3.2.4 on 2021-06-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210114_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_man',
            field=models.BooleanField(default=True),
        ),
    ]
