# Generated by Django 3.0.7 on 2020-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200612_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='Null', null=True, upload_to='products/product/detail/'),
        ),
    ]
