# Generated by Django 3.0.7 on 2020-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='original_image',
            field=models.ImageField(null=True, upload_to='media/images/blog/category'),
        ),
        migrations.AddField(
            model_name='post',
            name='original_image',
            field=models.ImageField(null=True, upload_to='media/images/blog/detail/'),
        ),
    ]
