# Generated by Django 3.0.7 on 2020-06-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200618_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='original_image',
            new_name='image',
        ),
    ]
