# Generated by Django 3.0.7 on 2020-06-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200618_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='original_image',
            new_name='image',
        ),
    ]
